version: 0.2

# Linux 사용자만 사용할 수 있습니다.이 buildspec 파일의 명령을 실행하는 Linux 사용자를 지정합니다.run-as를 지정하지 않으면 모든 명령이 root로 실행됩니다.
# run-as: 'ec2-user'

# 필수 시퀀스입니다. 빌드의 각 단계 동안 CodeBuild가 실행하는 명령을 나타냅니다
phases:
  # 설치 중에 CodeBuild가 실행하는 명령을 나타냅니다. 빌드 환경에서 패키지를 설치하는 경우에만 install 단계를 사용하는 것이 좋습니다. 예를 들어, Mocha나 RSpec 같은 코드 테스팅 프레임워크를 설치하기 위해 이 단계를 사용할 수 있습니다.
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo Insatlling NPM Packages and wget Enviorment File
  # 빌드 전에 CodeBuild가 실행하는 명령을 나타냅니다. 예를 들어, Amazon ECR에 로그인하기 위해 이 단계를 사용할 수 있습니다. 또는 npm 종속성을 설치할 수도 있습니다.
  pre_build:
    commands:
      - npm i
  # 빌드 중에 CodeBuild가 실행하는 명령을 나타냅니다. 예를 들어, Mocha, RSpec 또는 sbt를 실행하기 위해 이 단계를 사용할 수 있습니다.
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - ls
  # 빌드 후에 CodeBuild가 실행하는 명령을 나타냅니다(있는 경우). 예를 들어, Maven을 사용하여 빌드 결과물을 JAR 또는 WAR 파일에 패키지할 수 있으며, Amazon ECR에 Docker 이미지를 푸시할 수도 있습니다.
  post_build:
    commands:
      - echo Build started on `date`
# CodeBuild가 빌드 출력을 찾을 수 있는 위치 및 CodeBuild가 Amazon S3 출력 버킷에 업로드하기 위해 빌드 출력을 준비하는 방식에 대한 정보를 나타냅니다.
artifacts:
  # 빌드 환경의 빌드 출력 결과물을 포함하는 위치를 나타냅니다.
  files:
    - '**/*'
  # name: build-$(date +%Y-%m-%d)